import { load as parseYaml } from "js-yaml";
import { z } from "zod";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const featureConfigSchema = z
  .object({
    enabled: z.boolean(),
    config: z.record(z.string(), z.unknown()).optional(),
  })
  .strict();

const servicesConfigSchema = z
  .object({
    serviceCategories: z
      .array(
        z
          .object({
            id: z.string().min(1),
            name: z.string().min(1),
            iconName: z.string().min(1),
            description: z.string().min(1),
          })
          .strict()
      )
      .min(1),
    services: z
      .array(
        z
          .object({
            id: z.string().min(1),
            name: z.string().min(1),
            description: z.string().min(1),
            icon: z.string().min(1),
            iconName: z.string().min(1),
            href: z.string().url(),
            ping: z.string().url().optional(),
            category: z.string().min(1),
            isNew: z.boolean().optional(),
            isPopular: z.boolean().optional(),
          })
          .strict()
      )
      .min(1),
  })
  .strict();

const profileFieldSchema = z
  .object({
    enabled: z.boolean(),
    label: z.string().min(1),
    description: z.string().min(1),
    placeholder: z.string().min(1).optional(),
    inputType: z.enum(["text", "date", "url"]).optional(),
    required: z.boolean().optional(),
  })
  .strict();

const socialConnectorSchema = z
  .object({
    target: z.string().min(1),
    connectorId: z.string().min(1).optional(),
    enabled: z.boolean(),
    displayName: z.string().min(1).optional(),
    icon: z.string().min(1).optional(),
    description: z.string().min(1).optional(),
  })
  .strict();

const socialIdentitiesFeatureConfigSchema = z
  .object({
    enabled: z.boolean(),
    config: z
      .object({
        connectors: z.array(socialConnectorSchema).optional(),
      })
      .passthrough()
      .optional(),
  })
  .strict();

const featuresConfigSchema = z
  .object({
    features: z
      .object({
        emailChange: featureConfigSchema,
        phoneChange: featureConfigSchema,
        usernameChange: featureConfigSchema,
        mfa: z
          .object({
            totp: featureConfigSchema,
            backupCodes: featureConfigSchema,
            webAuthn: featureConfigSchema,
          })
          .strict(),
        passkey: featureConfigSchema,
        socialIdentities: socialIdentitiesFeatureConfigSchema,
        sessions: featureConfigSchema,
        accountDeletion: featureConfigSchema,
      })
      .strict(),
    profileFields: z
      .object({
        avatar: profileFieldSchema,
        name: profileFieldSchema,
        birthdate: profileFieldSchema,
        zoneinfo: profileFieldSchema,
        locale: profileFieldSchema,
        website: profileFieldSchema,
      })
      .strict(),
  })
  .strict();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, "..");

const configSourceDir = process.env.CONFIG_SOURCE_DIR
  ? isAbsolute(process.env.CONFIG_SOURCE_DIR)
    ? process.env.CONFIG_SOURCE_DIR
    : resolve(repoRoot, process.env.CONFIG_SOURCE_DIR)
  : resolve(repoRoot, "config/source");

const servicesSourcePath = resolve(configSourceDir, "services.yaml");
const featuresSourcePath = resolve(configSourceDir, "features.yaml");
const generatedServicesPath = resolve(repoRoot, "config/generated/services.ts");
const generatedFeaturesPath = resolve(repoRoot, "config/generated/features.ts");

const generatedBanner = `/**
 * Auto-generated by scripts/generate-config.mjs
 * Do not edit manually.
 */
`;

function readYamlFile(filePath) {
  const raw = readFileSync(filePath, "utf8");
  const parsed = parseYaml(raw);
  if (!parsed || typeof parsed !== "object") {
    throw new Error(`Invalid YAML root in ${filePath}`);
  }
  return parsed;
}

function ensureUniqueIds(items, itemName) {
  const ids = new Set();
  for (const item of items) {
    if (ids.has(item.id)) {
      throw new Error(`Duplicate ${itemName} id: ${item.id}`);
    }
    ids.add(item.id);
  }
}

function validateCrossReferences(serviceCategories, services) {
  const categoryIds = new Set(serviceCategories.map((category) => category.id));
  for (const service of services) {
    if (!categoryIds.has(service.category)) {
      throw new Error(
        `Service \"${service.id}\" references missing category \"${service.category}\"`
      );
    }
  }
}

function serializeObject(value) {
  return JSON.stringify(value, null, 2);
}

function createServicesModule(serviceCategories, services) {
  return `${generatedBanner}
import type { Service, ServiceCategory } from "@/config/types";
import {
  getServiceById as getServiceByIdFromList,
  getServicesByCategory as getServicesByCategoryFromList,
  searchServices as searchServicesFromList,
} from "@/lib/config/service-helpers";

export const serviceCategories: ServiceCategory[] = ${serializeObject(serviceCategories)};

export const services: Service[] = ${serializeObject(services)};

export function getServicesByCategory(categoryId: string): Service[] {
  return getServicesByCategoryFromList(services, categoryId);
}

export function getServiceById(id: string): Service | undefined {
  return getServiceByIdFromList(services, id);
}

export function searchServices(query: string): Service[] {
  return searchServicesFromList(services, query);
}
`;
}

function createFeaturesModule(features, profileFields) {
  return `${generatedBanner}
import type {
  FeaturesConfig,
  ProfileFieldConfig,
  ProfileFieldsConfig,
} from "@/config/types";
import {
  getEnabledProfileFields as getEnabledProfileFieldsFromConfig,
  isFeatureEnabled as isFeatureEnabledFromConfig,
} from "@/lib/config/feature-helpers";

export const features: FeaturesConfig = ${serializeObject(features)};

export const profileFields: ProfileFieldsConfig = ${serializeObject(profileFields)};

export function isFeatureEnabled<K extends keyof FeaturesConfig>(
  featureKey: K,
  subFeatureKey?: string
): boolean {
  return isFeatureEnabledFromConfig(features, featureKey, subFeatureKey);
}

export function getEnabledProfileFields(): Array<{
  key: keyof ProfileFieldsConfig;
  config: ProfileFieldConfig;
}> {
  return getEnabledProfileFieldsFromConfig(profileFields);
}
`;
}

function generate() {
  const servicesSourceRaw = readYamlFile(servicesSourcePath);
  const featuresSourceRaw = readYamlFile(featuresSourcePath);

  const servicesSource = servicesConfigSchema.parse(servicesSourceRaw);
  const featuresSource = featuresConfigSchema.parse(featuresSourceRaw);

  const serviceCategories = servicesSource.serviceCategories;
  const services = servicesSource.services;

  ensureUniqueIds(serviceCategories, "category");
  ensureUniqueIds(services, "service");
  validateCrossReferences(serviceCategories, services);

  const features = featuresSource.features;
  const profileFields = featuresSource.profileFields;

  writeFileSync(
    generatedServicesPath,
    createServicesModule(serviceCategories, services),
    "utf8"
  );
  writeFileSync(
    generatedFeaturesPath,
    createFeaturesModule(features, profileFields),
    "utf8"
  );

  console.log("Generated config modules:");
  console.log(`- ${generatedServicesPath}`);
  console.log(`- ${generatedFeaturesPath}`);
}

generate();
